version: "2"

networks:
  grafana:

volumes:
  app_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  #    - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana

  promtail:
    image: grafana/promtail:latest
    volumes:
      - app_data:/var/log
    networks:
      - grafana

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_RENDERING_SERVER_URL: http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      - GF_LOG_FILTERS: rendering:debug
    networks:
      - grafana
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports: 
      - 8081

 # app:
 #   build: ./app
 #   ports:
 #     - 8083:90
 #   volumes:
 #     - app_data:/var/log
 #   networks:
 #     - grafana

 # db:
 #   image: grafana/tns-db:latest
 #   ports:
 #     - 8084:90
 #   networks:
 #     - grafana
